# Site settings
name: "Daniella Cocco"
email: "d@daniellacoc.co"
baseurl: ""
url: "http://daniellacoc.co"

# Build settings
markdown: kramdown
permalink: pretty

# Custom collections
collections:
  - projects
